fortran-lang/registry

registry/src/App.css
registry/src/components/packageItem.js
registry/src/pages/Navbar.js
registry/src/pages/dashboard.js
registry/src/pages/search.js

fix: improvements in the registry.

---

README.md
flask/auth.py
flask/mongo.py
registry/src/pages/Navbar.js
registry/src/pages/account.js
registry/src/pages/login.js
registry/src/pages/package.js
registry/src/store/actions/authActions.js

Thanks and Regards,
Henil  
CC: @awvwgk @arteevraina @minhqdao @perazz

feat: clone the registry archive and minor fixes

---

registry/src/home.css
registry/src/pages/Navbar.js
registry/src/pages/home.js
registry/src/store/actions/searchActions.js
registry/src/store/reducers/searchReducer.js

feat: added the UI for Home Page.

---

registry/src/home.css
registry/src/pages/home.js

Testable link - https://registry-frontend-arteevraina.vercel.app/

fix: search bar alignment in big screens

---

flask/user.py
registry/src/App.css
registry/src/pages/dashboard.js

Testable Link - https://registry-frontend-arteevraina.vercel.app/

feat: show roles in the dashboard cards

---

flask/namespaces.py
flask/packages.py
registry/src/pages/dashboard.js
registry/src/pages/generatePackageTokenDialogForm.js
registry/src/store/actions/generatePackageTokenActions.js
registry/src/store/reducers/generatePackageTokenReducer.js
registry/src/store/reducers/rootReducer.js

Addresses: https://github.com/fortran-lang/registry/issues/19#issuecomment-1534158661

feat: implemented package specific token uploads

---

flask/namespaces.py
flask/packages.py

This Pull Request adds a fix for the crash mentioned https://github.com/fortran-lang/registry/pull/42#issuecomment-1578128855
https://github.com/fortran-lang/registry/pull/42#issuecomment-1578128855
Test out the admin APIs for deleting packages, package version &  namespace.
https://registry-apis.vercel.app/apidocs/#/

fix: add user not found condition to prevent crash

---

flask/documentation/get_namespace_admins.yaml
flask/documentation/get_namespace_maintainers.yaml
flask/documentation/package_maintainers.yaml
flask/namespaces.py
flask/packages.py
registry/src/pages/showUserListDialog.js
registry/src/store/actions/userListActions.js
registry/src/store/reducers/userListReducer.js
tests/test_namespaces.py
tests/test_packages.py

This PR adds security checks for the APIs related to fetching admins & maintainers. And verifies if the current user is authorized to fetch the details.
#44 
* https://registry-apis.vercel.app/apidocs
* https://registry-frontend-arteevraina.vercel.app

Security Checks for the APIs

---

flask/packages.py

fix: file type octet stream
#41 
fpm publish --token <your-token>
https://henilp105.vercel.app/

fix: file type octet stream

---

flask/packages.py

_List the contents of this PR._
_List all the relevant issues this PR addresses or closes._
_Always include a short set of instructions on how to test the changes made in this PR._
_Always provide a link which reviewers can use for testing._

fix: octet stream encoding

---

backend/app.py
backend/auth.py
backend/requirements.txt
backend/tests/base_case.py
backend/tests/test_login.py

feat: jwt token setup for Authentication APIs

---

backend/models/namespace.py
backend/namespaces.py
backend/packages.py
backend/tests/test_namespaces.py

refactor: added token security for namespaces APIs + models for Namespace.

---

.github/workflows/actions.yml
backend/models/package.py
backend/models/user.py
backend/packages.py
backend/tests/test_packages.py

Jwt packages

---

backend/app.py
backend/user.py
frontend/src/index.js
frontend/src/pages/Navbar.js
frontend/src/pages/createNamespace.js
frontend/src/pages/generateNamespaceTokenDialogForm.js
frontend/src/pages/generatePackageTokenDialogForm.js
frontend/src/pages/package.js
frontend/src/store/actions/authActions.js
frontend/src/store/actions/createNamespaceActions.js
frontend/src/store/actions/generateNamespaceTokenActions.js
frontend/src/store/actions/generatePackageTokenActions.js
frontend/src/store/reducers/authReducer.js

Frontend fixes jwt

---

backend/models/package.py
backend/packages.py

Report frontend

---

backend/packages.py
frontend/src/pages/package.js
frontend/src/pages/reportPackageForm.js
frontend/src/store/actions/reportPackageActions.js
frontend/src/store/reducers/reportPackageReducer.js
frontend/src/store/reducers/rootReducer.js

Report package UI

---

backend/packages.py
backend/user.py
frontend/package.json
frontend/src/pages/package.js
frontend/src/pages/packageRatingGraph.js
frontend/src/pages/reportPackageForm.js

feat: ratings API fixes and UI in place.

---

backend/packages.py
backend/user.py
frontend/src/pages/admin.js
frontend/src/pages/viewMalicousReports.js
frontend/src/store/actions/adminActions.js
frontend/src/store/actions/viewMalicousReportActions.js
frontend/src/store/reducers/rootReducer.js
frontend/src/store/reducers/viewMalicousReportsReducer.js

Reports UI

---

backend/check_digests.py
backend/validate.py

this PR fixes the validation bugs in the package validation CI.

fix: validation bugs

---

backend/validate.py

This PR introduces an interim bug fix for the package validation bug in fpm `v0.10.1` , this functionality will  be disabled with the upcoming release for the fpm.

fix: interim fix for package validation

---

.github/workflows/security_checks.yml
.github/workflows/tests.yml
backend/validate.py
frontend/src/components/packageItem.js
frontend/src/pages/package.js

This PR fixes the following functionalities:
Thanks and Regards,
Henil

fix: bugs, add: package maintainers should be visible to everyone , package data rendering bugs.

---

.github/workflows/security_checks.yml
.github/workflows/tests.yml
backend/models/namespace.py
backend/namespaces.py
backend/packages.py
backend/requirements.txt
backend/user.py
backend/validate.py
frontend/src/components/packageItem.js
frontend/src/pages/namespace.js
frontend/src/pages/package.js
frontend/src/pages/showUserListDialog.js

This PR patches some of the bugs and requests by the community.

fix: bugs detected in current release
